image: gradle:8.14.3-jdk21-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  # Variables pour Docker
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - checkstyle
  - build
  - test
  - publish

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

check-style:
  stage: checkstyle
  script:
    - gradle spotlessCheck
  allow_failure: false

build:
  stage: build
  script:
    - gradle build -x test -x spotlessCheck
  artifacts:
    paths:
      - build/libs/
    expire_in: 1 week

test:
  stage: test
  script:
    - gradle test
  artifacts:
    when: always
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
    paths:
      - build/test-results/
      - build/reports/tests/
    expire_in: 1 week

docker-build:
  stage: publish
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - apk add --no-cache curl git
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG -t $IMAGE_TAG_LATEST .
    - docker push $IMAGE_TAG
    - docker push $IMAGE_TAG_LATEST
  only:
    - main
    - master
    - tags
    - ci
  dependencies: []
